const uint16_t PROGMEM MOUSE_LAYER_TOGGLE[] = {LT1_SPC, LT5_BSP, COMBO_END};
const uint16_t PROGMEM CAPS_WORD_TOGGLE[] = {HOME_F, HOME_J, COMBO_END};

combo_t key_combos[] = {
    COMBO(MOUSE_LAYER_TOGGLE, TG(MOUSE_2)),
    COMBO(CAPS_WORD_TOGGLE, QK_CAPS_WORD_TOGGLE),
};
